spring.application.name=freeze
spring.devtools.remote.restart.enabled=true

# Enable the web-based H2 console interface
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection details
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=example

# Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true