spring.application.name=freeze
spring.devtools.remote.restart.enabled=true

# Enable the web-based H2 console interface
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection details
spring.datasource.url=jdbc:h2:mem:freeze-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=freeze
spring.datasource.password=password

# Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
